services:
  server-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=5173
    volumes:
      - ./frontend:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    ports:
      - "5173:5173"
    command: yarn run dev
    networks:
      - app-network
  server-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    ports:
      - '8085:8080'
    command: 'yarn run dev'
    depends_on:
      - db
    networks:
      - app-network
  # prisma-studio:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./server:/app
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   ports:
  #     - "5553:5555"
  #   command: npx prisma studio
  #   networks:
  #     - app-network
  db:
    image: mysql:8.0
    container_name: tonic-store
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Vietnam
    volumes:
      - ./docker/db/data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge