services:
  server-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure
    ports:
      - "5173:5173"
    command: yarn run dev
    networks:
      - app-network

  server-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    ports:
      - '8085:8085'
    command: 'yarn run dev'
    depends_on:
      - db
    networks:
      - app-network

  server-fe-admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - ./admin/.env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure
    ports:
      - "3001:3001"
    command: yarn run dev
    networks:
      - app-network

  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5555:5555"
    command: npx prisma studio
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: tonic-store
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      TZ: Asia/Vietnam
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "9000:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
