name: Build and Push

on:
  push:
    branches: [main, develop]

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set SHORT_SHA
        id: short_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set variables
        id: vars
        run: echo "image_prefix=$(echo '${{ github.repository_owner }}/tonic-store' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/backend:${{ steps.short_sha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/frontend:${{ steps.short_sha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Admin image
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          file: ./admin/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/admin:${{ steps.short_sha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_prefix }}/admin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cleanup Docker after build
        if: always()
        run: docker system prune -f
